// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaCertoForms.Models;

namespace TaCertoForms.Migrations
{
    [DbContext(typeof(TaCertoFormsContext))]
    [Migration("20191019164701_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaCertoForms.Models.Atividade", b =>
                {
                    b.Property<int>("IdAtividade")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<int>("IdTurmaDisciplinaProfessor");

                    b.Property<bool>("IsAleatorio");

                    b.Property<bool>("IsProva");

                    b.Property<int>("NumeroTentativas");

                    b.HasKey("IdAtividade");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("TaCertoForms.Models.AtividadeRespostaAluno", b =>
                {
                    b.Property<int>("IdAtividadeRespostaAluno")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataEnvio");

                    b.Property<int>("IdAluno");

                    b.Property<int>("IdAtividade");

                    b.Property<float>("Nota");

                    b.Property<string>("TempoTotal");

                    b.HasKey("IdAtividadeRespostaAluno");

                    b.ToTable("AtividadeRespostaAlunos");
                });

            modelBuilder.Entity("TaCertoForms.Models.Disciplina", b =>
                {
                    b.Property<int>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("IdDisciplina");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("TaCertoForms.Models.DisciplinaTurma", b =>
                {
                    b.Property<int>("IdDisciplinaTurma")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDisciplina");

                    b.Property<int>("IdTurma");

                    b.HasKey("IdDisciplinaTurma");

                    b.ToTable("DisciplinaTurmas");
                });

            modelBuilder.Entity("TaCertoForms.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("Cidade");

                    b.Property<string>("Complemento");

                    b.Property<string>("Logradouro");

                    b.Property<int>("Numero");

                    b.Property<string>("Pais");

                    b.Property<string>("UF");

                    b.HasKey("IdEndereco");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("TaCertoForms.Models.Instituicao", b =>
                {
                    b.Property<int>("IdInstituicao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ");

                    b.Property<string>("Email");

                    b.Property<int>("IdEnderecoCobranca");

                    b.Property<int>("IdEnderecoPrincipal");

                    b.Property<string>("NomeFantasia");

                    b.Property<string>("RazaoSocial");

                    b.Property<string>("Telefone");

                    b.HasKey("IdInstituicao");

                    b.ToTable("Instituicaos");
                });

            modelBuilder.Entity("TaCertoForms.Models.Licenca", b =>
                {
                    b.Property<int>("IdLicenca")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdInstituicao");

                    b.Property<int>("NumeroDeLinceca");

                    b.Property<string>("ValidadeLicenca");

                    b.HasKey("IdLicenca");

                    b.ToTable("Licencas");
                });

            modelBuilder.Entity("TaCertoForms.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("TaCertoForms.Models.PerfilPessoa", b =>
                {
                    b.Property<int>("IdPerfilPessoa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPerfil");

                    b.Property<int>("IdPessoa");

                    b.HasKey("IdPerfilPessoa");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("IdPessoa");

                    b.ToTable("PerfilPessoa");
                });

            modelBuilder.Entity("TaCertoForms.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF");

                    b.Property<string>("Email");

                    b.Property<int>("IdInstituicao");

                    b.Property<string>("Nome");

                    b.Property<int?>("PerfilIdPerfil");

                    b.Property<string>("Senha");

                    b.HasKey("IdPessoa");

                    b.HasIndex("PerfilIdPerfil");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("TaCertoForms.Models.Questao", b =>
                {
                    b.Property<int>("IdQuestao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Enunciado");

                    b.Property<int>("IdAtividade");

                    b.Property<int>("IdTipoQuestao");

                    b.Property<string>("JsonQuestao");

                    b.Property<int>("PesoNota");

                    b.Property<string>("Titulo");

                    b.HasKey("IdQuestao");

                    b.ToTable("Questaos");
                });

            modelBuilder.Entity("TaCertoForms.Models.Turma", b =>
                {
                    b.Property<int>("IdTurma")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdInstituicao");

                    b.Property<int>("Periodo");

                    b.Property<string>("Serie");

                    b.HasKey("IdTurma");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("TaCertoForms.Models.TurmaAluno", b =>
                {
                    b.Property<int>("IdTurmaAluno")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPessoa");

                    b.Property<int>("IdTurma");

                    b.HasKey("IdTurmaAluno");

                    b.ToTable("TurmaAlunos");
                });

            modelBuilder.Entity("TaCertoForms.Models.TurmaDisciplinaProfessor", b =>
                {
                    b.Property<int>("IdTurmaDisciplinaProfessor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDisciplinaTurma");

                    b.Property<int>("IdProfessor");

                    b.HasKey("IdTurmaDisciplinaProfessor");

                    b.ToTable("TurmaDisciplinaProfessors");
                });

            modelBuilder.Entity("TaCertoForms.Models.PerfilPessoa", b =>
                {
                    b.HasOne("TaCertoForms.Models.Perfil", "Perfil")
                        .WithMany("PerfilPessoas")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaCertoForms.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaCertoForms.Models.Pessoa", b =>
                {
                    b.HasOne("TaCertoForms.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilIdPerfil");
                });
#pragma warning restore 612, 618
        }
    }
}
