CREATE SCHEMA Geral
AUTHORIZATION dbo;
CREATE SCHEMA TaCerto
AUTHORIZATION dbo;
CREATE SCHEMA TaCertoForms
AUTHORIZATION dbo;

CREATE TABLE `Geral.Pessoa` (
	`PessoaId` INT NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(255) NOT NULL,
	`Sobrenome` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`CPF` VARCHAR(11),
	`DataNascimento` DATE,
	PRIMARY KEY (`PessoaId`)
);
CREATE TABLE `Geral.Sistema` (
	`SistemaId` INT NOT NULL AUTO_INCREMENT,
	`Nome` VARCHAR(255) NOT NULL,
	`Descricao` TEXT NOT NULL,
	PRIMARY KEY (`SistemaId`)
);